apiVersion: v1
kind: Service
metadata:
  name: asr-service
  namespace: dev
  labels:
    app: asr-service
spec:
  selector:
    app: asr-service
  ports:
    - port: 8087
      targetPort: 8087
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-service
  namespace: dev
  labels:
    app: asr-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asr-service
  template:
    metadata:
      labels:
        app: asr-service
    spec:
      nodeSelector:
      tolerations:
      - key: "node-type"
        operator: Equal
        value: cpu
        effect: NoSchedule
      containers:
      - name: asr-service
        image: 662074586476.dkr.ecr.ap-south-1.amazonaws.com/ai4voice/asr-service:v1.1
        ports:
        - containerPort: 8087
        env:
        - name: ENV_FILE
          value: ".env"
        envFrom:
        - configMapRef:
            name: asr-service-config
        - secretRef:
            name: asr-service-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8087
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8087
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
