apiVersion: v1
kind: Service
metadata:
  name: asr-service
  namespace: dev
  labels:
    app: asr-service
spec:
  selector:
    app: asr-service
  ports:
    - port: 8087
      targetPort: 8087
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-service
  namespace: dev
  labels:
    app: asr-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asr-service
  template:
    metadata:
      labels:
        app: asr-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - ip-30-0-4-22.ap-south-1.compute.internal
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
        - "10.100.0.10"
        searches:
        - "dev.svc.cluster.local"
        - "svc.cluster.local"
        - "cluster.local"
      nodeSelector:
      tolerations:
      - key: "node-type"
        operator: Equal
        value: cpu
        effect: NoSchedule
      initContainers:
      - name: wait-for-db
        image: busybox:1.36
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for PostgreSQL to be ready..."
          MAX_ATTEMPTS=60
          ATTEMPT=0

          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
            # Check if PostgreSQL port is accessible using FQDN
            if nc -w 2 -z postgres.dev.svc.cluster.local 5432 2>/dev/null; then
              echo "PostgreSQL is ready!"
              exit 0
            fi
            ATTEMPT=$((ATTEMPT + 1))
            if [ $((ATTEMPT % 5)) -eq 0 ]; then
              echo "Attempt $ATTEMPT/$MAX_ATTEMPTS: Waiting for postgres.dev.svc.cluster.local:5432..."
            fi
            sleep 2
          done
          echo "ERROR: PostgreSQL not available after $MAX_ATTEMPTS attempts"
          exit 1
      containers:
      - name: asr-service
        image: 662074586476.dkr.ecr.ap-south-1.amazonaws.com/ai4voice/asr-service:19112025-172102-IST
        ports:
        - containerPort: 8087
        envFrom:
        - configMapRef:
            name: asr-service-config
        - secretRef:
            name: asr-service-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "1"
        startupProbe:
          httpGet:
            path: /health
            port: 8087
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 24
        livenessProbe:
          httpGet:
            path: /health
            port: 8087
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8087
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
