apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: dev
  labels:
    app: api-gateway-service
spec:
  selector:
    app: api-gateway-service
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP

