"""auto_20260309_143948

Revision ID: e3ecddc7271e
Revises: 
Create Date: 2026-03-09 14:39:48.949539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ecddc7271e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smr_tenant_policies',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('latency_policy', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('cost_policy', sa.String(length=20), server_default='tier_2', nullable=False),
    sa.Column('accuracy_policy', sa.String(length=20), server_default='standard', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smr_tenant_policies')
    # ### end Alembic commands ###
