apiVersion: v1
kind: Service
metadata:
  name: indictrans-nmt-service
  namespace: dev
  labels:
    app: indictrans-nmt
    component: ai-model
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: grpc
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: metrics
  selector:
    app: indictrans-nmt
---
apiVersion: v1
kind: Service
metadata:
  name: indictrans-nmt-nodeport
  namespace: dev
  labels:
    app: indictrans-nmt
    component: ai-model
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30083
    protocol: TCP
    name: http
  - port: 8001
    targetPort: 8001
    nodePort: 30084
    protocol: TCP
    name: grpc
  - port: 8002
    targetPort: 8002
    nodePort: 30085
    protocol: TCP
    name: metrics
  selector:
    app: indictrans-nmt
