# Docker Compose Override for Local Development
# This file is automatically merged with docker-compose.yml by Docker Compose
# Use this file for local development customizations

version: '3.8'

services:
  # API Gateway Service - Development overrides
  api-gateway-service:
    volumes:
      - ./services/api-gateway-service:/app
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - TTS_SERVICE_URL=http://tts-service:8088

  # Auth Service - Development overrides
  auth-service:
    volumes:
      - ./services/auth-service:/app
    # command: removed to avoid conflict with Dockerfile ENTRYPOINT
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG

  # Config Service - Development overrides
  config-service:
    volumes:
      - ./services/config-service:/app
    # command: uvicorn main:app --host 0.0.0.0 --port 8082 --reload
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG

  # Metrics Service - Development overrides
  metrics-service:
    volumes:
      - ./services/metrics-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8083 --reload
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG

  # Telemetry Service - Development overrides
  telemetry-service:
    volumes:
      - ./services/telemetry-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8084 --reload
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG

  # Alerting Service - Development overrides
  alerting-service:
    volumes:
      - ./services/alerting-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8085 --reload
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG

  # Dashboard Service - Development overrides
  dashboard-service:
    volumes:
      - ./services/dashboard-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8086 --reload
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG

  # ASR Service - Development overrides
  asr-service:
    environment:
      - TRITON_ENDPOINT=http://13.200.133.97:5000

  # Pipeline Service - Development overrides
  pipeline-service:
    volumes:
      - ./services/pipeline-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8090 --reload
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG

  # PostgreSQL - Development overrides
  postgres:
    environment:
      - POSTGRES_LOG_STATEMENT=all
      - POSTGRES_LOG_MIN_DURATION_STATEMENT=0
    ports:
      - "5434:5432"  # Expose for external tools

  # Redis - Development overrides
  redis:
    ports:
      - "6381:6379"  # Expose for external tools

  # InfluxDB - Development overrides
  influxdb:
    ports:
      - "8089:8086"  # Expose for external tools

  # Elasticsearch - Development overrides
  elasticsearch:
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable security for development
    ports:
      - "9203:9200"  # Expose for external tools

  # Kafka - Development overrides
  kafka:
    ports:
      - "9093:9092"  # Expose for external tools

  # Zookeeper - Development overrides
  zookeeper:
    ports:
      - "2182:2181"  # Expose for external tools

# Note: This file is for local development only
# Do not use this file in production environments
# The override file provides:
# - Hot-reloading for code changes
# - Debug logging
# - Port exposure for external tools
# - Development-specific environment variables

