"""auto_20260309_161209

Revision ID: e288aa060342
Revises: 
Create Date: 2026-03-09 16:12:09.921128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e288aa060342'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_enrichment_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('source_field', sa.String(length=255), nullable=False),
    sa.Column('target_field', sa.String(length=255), nullable=False),
    sa.Column('enrichment_type', sa.String(length=50), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_name')
    )
    op.create_index('idx_data_enrichment_rules_active', 'data_enrichment_rules', ['is_active'], unique=False)
    op.create_index('idx_data_enrichment_rules_rule_name', 'data_enrichment_rules', ['rule_name'], unique=False)
    op.create_table('event_correlations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_count', sa.Integer(), server_default='1', nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_correlations_correlation_id', 'event_correlations', ['correlation_id'], unique=False)
    op.create_index('idx_event_correlations_event_type', 'event_correlations', ['event_type'], unique=False)
    op.create_index('idx_event_correlations_first_seen', 'event_correlations', ['first_seen'], unique=False)
    op.create_index('idx_event_correlations_last_seen', 'event_correlations', ['last_seen'], unique=False)
    op.create_table('log_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.String(length=255), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_id')
    )
    op.create_index('idx_log_metadata_correlation_id', 'log_metadata', ['correlation_id'], unique=False)
    op.create_index('idx_log_metadata_created_at', 'log_metadata', ['created_at'], unique=False)
    op.create_index('idx_log_metadata_log_id', 'log_metadata', ['log_id'], unique=False)
    op.create_index('idx_log_metadata_service_correlation', 'log_metadata', ['service_name', 'correlation_id'], unique=False)
    op.create_index('idx_log_metadata_service_name', 'log_metadata', ['service_name'], unique=False)
    op.create_table('trace_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=255), nullable=False),
    sa.Column('span_id', sa.String(length=255), nullable=False),
    sa.Column('parent_span_id', sa.String(length=255), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('operation_name', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trace_metadata_created_at', 'trace_metadata', ['created_at'], unique=False)
    op.create_index('idx_trace_metadata_parent_span_id', 'trace_metadata', ['parent_span_id'], unique=False)
    op.create_index('idx_trace_metadata_service_name', 'trace_metadata', ['service_name'], unique=False)
    op.create_index('idx_trace_metadata_span_id', 'trace_metadata', ['span_id'], unique=False)
    op.create_index('idx_trace_metadata_trace_id', 'trace_metadata', ['trace_id'], unique=False)
    op.create_index('idx_trace_metadata_trace_span', 'trace_metadata', ['trace_id', 'span_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trace_metadata_trace_span', table_name='trace_metadata')
    op.drop_index('idx_trace_metadata_trace_id', table_name='trace_metadata')
    op.drop_index('idx_trace_metadata_span_id', table_name='trace_metadata')
    op.drop_index('idx_trace_metadata_service_name', table_name='trace_metadata')
    op.drop_index('idx_trace_metadata_parent_span_id', table_name='trace_metadata')
    op.drop_index('idx_trace_metadata_created_at', table_name='trace_metadata')
    op.drop_table('trace_metadata')
    op.drop_index('idx_log_metadata_service_name', table_name='log_metadata')
    op.drop_index('idx_log_metadata_service_correlation', table_name='log_metadata')
    op.drop_index('idx_log_metadata_log_id', table_name='log_metadata')
    op.drop_index('idx_log_metadata_created_at', table_name='log_metadata')
    op.drop_index('idx_log_metadata_correlation_id', table_name='log_metadata')
    op.drop_table('log_metadata')
    op.drop_index('idx_event_correlations_last_seen', table_name='event_correlations')
    op.drop_index('idx_event_correlations_first_seen', table_name='event_correlations')
    op.drop_index('idx_event_correlations_event_type', table_name='event_correlations')
    op.drop_index('idx_event_correlations_correlation_id', table_name='event_correlations')
    op.drop_table('event_correlations')
    op.drop_index('idx_data_enrichment_rules_rule_name', table_name='data_enrichment_rules')
    op.drop_index('idx_data_enrichment_rules_active', table_name='data_enrichment_rules')
    op.drop_table('data_enrichment_rules')
    # ### end Alembic commands ###
