"""auto_20260309_135857

Revision ID: 6807125a520a
Revises: ccb259d8023a
Create Date: 2026-03-09 13:58:58.759782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6807125a520a'
down_revision: Union[str, None] = 'ccb259d8023a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
