apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: dev
type: Opaque
data:
  # Add your secret environment variables here in base64
  # Example:
  # JWT_SECRET: eW91cl9qd3Rfc2VjcmV0  # your_jwt_secret in base64
  # ENCRYPTION_KEY: eW91cl9lbmNyeXB0aW9uX2tleQ==  # your_encryption_key in base64
