"""auto_20260407_143656

Revision ID: 265a08f8fbff
Revises: b1c2d3e4f5a6
Create Date: 2026-04-07 14:36:56.558963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265a08f8fbff'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'models', ['model_id'])
    op.create_foreign_key(None, 'services', 'models', ['model_id'], ['model_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_constraint(None, 'models', type_='unique')
    # ### end Alembic commands ###
