"""auto_20260430_175520

Revision ID: ba599916953b
Revises: 500e60023e47
Create Date: 2026-04-30 17:55:21.208496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba599916953b'
down_revision: Union[str, None] = '500e60023e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('services', sa.Column('billing_unit_type', sa.String(length=32), nullable=True))
    op.add_column('services', sa.Column('tier', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'tier')
    op.drop_column('services', 'billing_unit_type')
    op.drop_column('services', 'cost_per_unit')
    # ### end Alembic commands ###
