apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: dev
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: client
    - port: 9093
      targetPort: 9093
      protocol: TCP
      name: inter-broker
  type: ClusterIP
