# Transliteration Service - Public API (as exposed via API Gateway)
openapi: 3.0.3
info:
  title: Transliteration Service
  description: Transliterate text between scripts (e.g. Latin to Indic).
  version: 1.0.0
servers:
  - url: "http://localhost:8080"
    description: API Gateway
tags:
  - name: Transliteration
paths:
  /api/v1/transliteration/inference:
    post:
      tags: [Transliteration]
      summary: Transliteration inference
      security: [{ BearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/TransliterationInferenceRequest" }
      responses:
        "200":
          content:
            application/json:
              schema: { $ref: "#/components/schemas/TransliterationInferenceResponse" }
        "401": { description: Unauthorized }
  /api/v1/transliteration/models:
    get:
      tags: [Transliteration]
      summary: List models
      security: [{ BearerAuth: [] }]
      responses:
        "200": { description: List of models }
  /api/v1/transliteration/services:
    get:
      tags: [Transliteration]
      summary: List services
      security: [{ BearerAuth: [] }]
      responses:
        "200": { description: List of services }
  /api/v1/transliteration/languages:
    get:
      tags: [Transliteration]
      summary: List languages
      security: [{ BearerAuth: [] }]
      responses:
        "200": { description: List of languages }
  /api/v1/transliteration/health:
    get:
      tags: [Transliteration]
      summary: Health check
      responses:
        "200": { description: Health status }
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
  schemas:
    TransliterationLanguagePair:
      type: object
      required: [sourceLanguage, targetLanguage]
      properties:
        sourceLanguage: { type: string, description: "Source language code (e.g. 'en', 'hi', 'ta')" }
        targetLanguage: { type: string, description: Target language code }
        sourceScriptCode: { type: string, description: "Script code for source (e.g. 'Deva', 'Arab')" }
        targetScriptCode: { type: string, description: Script code for target }
    TransliterationTextInput:
      type: object
      required: [source]
      properties:
        source: { type: string, description: Input text to transliterate }
    TransliterationInferenceConfig:
      type: object
      required: [language]
      properties:
        serviceId: { type: string, description: Transliteration service/model ID (optional; Smart Router will assign if omitted) }
        language: { $ref: "#/components/schemas/TransliterationLanguagePair" }
        isSentence: { type: boolean, default: true, description: True for sentence-level, False for word-level }
        numSuggestions: { type: integer, default: 0, description: "Top-k suggestions (0=best, >0 word-level only, max 10)" }
    TransliterationInferenceRequest:
      type: object
      required: [input, config]
      properties:
        input:
          type: array
          minItems: 1
          maxItems: 100
          items: { $ref: "#/components/schemas/TransliterationTextInput" }
        config: { $ref: "#/components/schemas/TransliterationInferenceConfig" }
        controlConfig: { type: object, description: Additional control parameters }
    TransliterationOutput:
      type: object
      properties:
        source: { type: string, description: Source text }
        target: { type: string, description: Transliterated text }
        suggestions: { type: array, items: { type: string }, description: Top-k suggestions when numSuggestions > 0 }
    TransliterationInferenceResponse:
      type: object
      properties:
        output:
          type: array
          items: { $ref: "#/components/schemas/TransliterationOutput" }
security:
  - BearerAuth: []
