from sqlalchemy import (
    CHAR,
    BigInteger,
    CheckConstraint,
    Column,
    Computed,
    Date,
    DateTime,
    ForeignKey,
    Identity,
    Index,
    Integer,
    Numeric,
    PrimaryKeyConstraint,
    String,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func

from app.models import Base
from app.models.pay_per_use.usage_event import MONEY, UNITS

# The rollup's upsert target (ON CONFLICT). NULLs count as equal, so rows
# with an unknown application or API key still upsert instead of duplicating.
DIMENSION_KEY = "uq_daily_usage_dimensions"
DIMENSIONS = (
    "usage_date", "tenant_id", "application_id", "api_key_id",
    "tier_id", "service_id", "inference_type_id", "billing_month",
)


class DailyUsage(Base):
    """Daily rollup of usage_events; table created by migration 4c6e8a0b2d3f.

    One row per usage_date and dimension combination (DIMENSIONS). Names and
    the tenant's budget are copied in by the rollup so dashboard reads need no
    cross-database joins. cost is generated by Postgres from the three
    category costs; the rollup writes the parts, never cost.

    Range-partitioned on usage_date by calendar month (see partitioning.py).
    The primary key is (id, usage_date) because Postgres requires the
    partition column in every unique key.

    tenant_id, application_id and api_key_id are rows in the auth DB, so they
    have no foreign key.
    """

    __tablename__ = "daily_usage"
    __table_args__ = (
        PrimaryKeyConstraint("id", "usage_date", name="pk_daily_usage"),
        CheckConstraint("billing_month ~ '^[0-9]{4}-[0-9]{2}$'", name="ck_daily_usage_billing_month"),
        CheckConstraint("success_count + failed_count = request_count", name="ck_daily_usage_request_counts"),
        Index(DIMENSION_KEY, *DIMENSIONS, unique=True, postgresql_nulls_not_distinct=True),
        Index("ix_daily_usage_tenant_date", "tenant_id", "usage_date"),
        Index("ix_daily_usage_application_date", "application_id", "usage_date"),
        Index("ix_daily_usage_service_date", "service_id", "usage_date"),
        Index("ix_daily_usage_billing_month", "billing_month", "tenant_id"),
        {"postgresql_partition_by": "RANGE (usage_date)"},
    )

    id = Column(BigInteger, Identity(always=True), nullable=False)
    usage_date = Column(Date, nullable=False)

    tenant_id = Column(Integer, nullable=True)
    tenant_name = Column(String(255), nullable=True)
    allocated_budget = Column(Numeric(15, 2), nullable=True)
    application_id = Column(Integer, nullable=True)
    application_name = Column(String(255), nullable=True)
    api_key_id = Column(Integer, nullable=True)
    tier_id = Column(
        UUID(as_uuid=True),
        ForeignKey("tiers.id", ondelete="SET NULL", name="fk_daily_usage_tier_id"),
        nullable=True,
    )
    tier_name = Column(String(255), nullable=True)
    service_id = Column(
        String(255),
        ForeignKey("mm_services.service_id", name="fk_daily_usage_service_id"),
        nullable=True,
    )
    service_name = Column(String(255), nullable=True)
    model_name = Column(String(255), nullable=True)
    inference_type_id = Column(
        Integer,
        ForeignKey("inference_types.id", name="fk_daily_usage_inference_type_id"),
        nullable=True,
    )
    task_type = Column(String(64), nullable=True)
    unit = Column(String(64), nullable=True)
    billing_month = Column(CHAR(7), nullable=False)

    request_count = Column(BigInteger, nullable=False, default=0, server_default="0")
    success_count = Column(BigInteger, nullable=False, default=0, server_default="0")
    failed_count = Column(BigInteger, nullable=False, default=0, server_default="0")

    total_units = Column(UNITS, nullable=False, default=0, server_default="0")
    cached_input_units = Column(UNITS, nullable=False, default=0, server_default="0")
    output_units = Column(UNITS, nullable=False, default=0, server_default="0")

    input_units_cost = Column(MONEY, nullable=False, default=0, server_default="0")
    cached_input_units_cost = Column(MONEY, nullable=False, default=0, server_default="0")
    output_units_cost = Column(MONEY, nullable=False, default=0, server_default="0")
    # Generated: never set it (see UsageEvent.total_cost).
    cost = Column(
        MONEY,
        Computed("input_units_cost + cached_input_units_cost + output_units_cost", persisted=True),
        nullable=False,
    )

    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    # Set by the rollup on every upsert; the default only covers the first insert.
    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
