from sqlalchemy import (
    CheckConstraint,
    Column,
    Computed,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    PrimaryKeyConstraint,
    SmallInteger,
    String,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func

from app.models import Base

# Units are unbounded (tokens, characters, minutes ...); money is INR.
UNITS = Numeric()
MONEY = Numeric(18, 6)


class UsageEvent(Base):
    """One billed span (API-key traffic); table created by migration 3b5d7f9a1c2e.

    A request normally has one span; a TTS per_item request has one per chunk,
    all sharing the correlation id. Costs are split by category: for LLM the
    split is real, for other task types the whole charge is in
    input_units_cost. total_cost is generated by Postgres from the three.

    Range-partitioned on occurred_at by UTC month (see partitioning.py).
    occurred_at is the span's end time, the instant billing_month is derived
    from, so it must be set by the writer; created_at is only the insert time.
    The primary key includes occurred_at because Postgres requires the
    partition column in every unique key, and a Kafka redelivery of the same
    span hits it instead of adding a row.

    tenant_id, application_id and api_key_id are rows in the auth DB, so they
    have no foreign key.
    """

    __tablename__ = "usage_events"
    __table_args__ = (
        PrimaryKeyConstraint("correlation_id", "span_id", "occurred_at", name="pk_usage_events"),
        CheckConstraint(
            "cached_input_units >= 0 AND output_units >= 0 AND cached_input_units + output_units <= total_units",
            name="ck_usage_events_units",
        ),
        Index("ix_usage_events_tenant_occurred", "tenant_id", "occurred_at"),
        Index("ix_usage_events_api_key_occurred", "api_key_id", "occurred_at"),
        Index("ix_usage_events_service_occurred", "service_id", "occurred_at"),
        {"postgresql_partition_by": "RANGE (occurred_at)"},
    )

    correlation_id = Column(String(64), nullable=False)
    span_id = Column(String(32), nullable=False)
    occurred_at = Column(DateTime(timezone=True), nullable=False)

    tenant_id = Column(Integer, nullable=True)
    application_id = Column(Integer, nullable=True)
    api_key_id = Column(Integer, nullable=True)
    tier_id = Column(
        UUID(as_uuid=True),
        ForeignKey("tiers.id", ondelete="SET NULL", name="fk_usage_events_tier_id"),
        nullable=True,
    )
    service_id = Column(
        String(255),
        ForeignKey("mm_services.service_id", name="fk_usage_events_service_id"),
        nullable=True,
    )
    inference_type_id = Column(
        Integer,
        ForeignKey("inference_types.id", name="fk_usage_events_inference_type_id"),
        nullable=True,
    )
    task_type = Column(String(64), nullable=True)
    unit_of_measurement = Column(String(64), nullable=True)
    status_code = Column(SmallInteger, nullable=True)

    # cached_input_units and output_units are parts of total_units.
    total_units = Column(UNITS, nullable=False, default=0, server_default="0")
    cached_input_units = Column(UNITS, nullable=False, default=0, server_default="0")
    output_units = Column(UNITS, nullable=False, default=0, server_default="0")

    input_units_cost = Column(MONEY, nullable=False, default=0, server_default="0")
    cached_input_units_cost = Column(MONEY, nullable=False, default=0, server_default="0")
    output_units_cost = Column(MONEY, nullable=False, default=0, server_default="0")
    # Generated: never set it. Each cost is rounded to MONEY's scale when
    # stored, so this always equals the sum of the stored parts.
    total_cost = Column(
        MONEY,
        Computed("input_units_cost + cached_input_units_cost + output_units_cost", persisted=True),
        nullable=False,
    )

    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
