apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: dev
  labels:
    app: api-gateway-service
spec:
  selector:
    app: api-gateway-service
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  namespace: dev
  labels:
    app: api-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      nodeSelector:
      tolerations:
      - key: "node-type"
        operator: Equal
        value: cpu
        effect: NoSchedule
      containers:
      - name: api-gateway-service
        image: 662074586476.dkr.ecr.ap-south-1.amazonaws.com/ai4voice/api-gateway-service:27112025-101836-IST
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: api-gateway-config
        - secretRef:
            name: api-gateway-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
