apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: dev
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
  type: ClusterIP
