apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-ebs-immediate
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
