"""
Shared FastAPI dependencies for authentication and authorization.

Permission checks use permission_ids (int) from JWT — zero DB round-trip.
ADMIN role bypasses all checks.

Two token families are supported:

  1. JWT (RS256)
     Authorization: Bearer eyJhbGci...
     → Verified via JWTVerifier (RS256 + JWKS)

  2. Opaque API key (32-char hex, secrets.token_hex(16))
     Authorization: <raw-key>         ← no Bearer prefix
     Authorization: Bearer <raw-key>  ← also accepted
     → Validated via Redis: auth:apikey:{token}
     → Redis value: {"token_id": "...", "permissions": [1,2,...], "user_id": <int>}
     → Raises InvalidAPIKeyError if key absent (revoked/expired/unknown)

Usage::

    from ai4icore_auth.dependencies import create_require_auth, create_require_role

    require_auth = create_require_auth(jwt_verifier)

    @router.post("/inference")
    async def infer(claims: AuthClaims = Depends(require_auth)):
        ...
"""

import json
import logging
import re
from typing import Optional

from fastapi import Depends, Header, Request

from .jwt_verifier import AuthClaims, JWTVerifier, JWTVerificationError, JWTExpiredError
from .permission_checker import PermissionChecker

logger = logging.getLogger(__name__)

# Redis key prefix — must match auth:apikey: prefix in auth-service CacheService
_API_KEY_REDIS_PREFIX = "auth:apikey:"


# ── Token-type discriminator ──────────────────────────────────────────────────

def _is_api_key(token: str) -> bool:
    """
    Return True for opaque hex API keys generated by secrets.token_hex(16).
    A JWT always has 3 dot-separated base64url parts; a 32-char hex string never does.
    """
    return bool(re.fullmatch(r"[0-9a-f]{32}", token))


# ── API-key validation (Redis fast path) ─────────────────────────────────────

async def _validate_api_key(token: str, request: Request) -> AuthClaims:
    """
    Validate an opaque API key directly from Redis.

    Redis key   : auth:apikey:{token}
    Redis value : {"token_id": "...", "permissions": [1, 2, ...], "user_id": <int|null>}

    Raises:
        InvalidAPIKeyError  – key absent (never issued, revoked, or expired)
        InvalidAPIKeyError  – Redis not available on request.app.state
    """
    from ai4icore_exceptions import InvalidAPIKeyError

    redis_client = getattr(request.app.state, "redis_client", None)
    if redis_client is None:
        logger.error(
            "API key validation failed: redis_client not found on app.state. "
            "Ensure the service initialises app.state.redis_client at startup."
        )
        raise InvalidAPIKeyError(
            "API key validation is unavailable. Please contact your administrator."
        )

    redis_key = f"{_API_KEY_REDIS_PREFIX}{token}"
    try:
        raw = await redis_client.get(redis_key)
    except Exception as exc:
        logger.error("Redis error during API key lookup: %s", exc)
        raise InvalidAPIKeyError(
            "API key validation is temporarily unavailable. Please try again."
        )

    if raw is None:
        raise InvalidAPIKeyError("APIKey has been revoked")

    try:
        data: dict = json.loads(raw)
    except (ValueError, TypeError) as exc:
        logger.error("Corrupt API key data in Redis for key %s…: %s", token[:8], exc)
        raise InvalidAPIKeyError("API key data is corrupted. Please re-issue the key.")

    permission_ids: list[int] = data.get("permissions", [])
    user_id: int = int(data["user_id"]) if data.get("user_id") else 0

    if user_id == 0:
        # Older keys stored without user_id — log once so it's visible in service logs.
        logger.warning(
            "API key %s… resolved without user_id (old Redis entry). "
            "Re-issue the key to attach user context.",
            token[:8],
        )

    return AuthClaims(
        user_id=user_id,
        permission_ids=permission_ids,
        roles=[],
        token_type="api_key",
        token_id=token,
    )


# ── Shared request.state population helper ───────────────────────────────────

def _populate_request_state(request: Request, claims: AuthClaims) -> None:
    """Write auth claims into request.state so all downstream code sees them."""
    request.state.user_id = claims.user_id
    request.state.tenant_id = claims.tenant_id
    request.state.permission_ids = claims.permission_ids
    request.state.roles = claims.roles
    request.state.token_type = claims.token_type
    request.state.token_id = claims.token_id
    request.state.username = claims.username
    request.state.email = claims.email
    request.state.is_authenticated = True
    request.state.jwt_claims = claims


# ── Public factory functions ──────────────────────────────────────────────────

def create_require_auth(jwt_verifier: JWTVerifier):
    """
    Returns a FastAPI dependency that accepts either a JWT or an opaque API key.

    - JWT path  : unchanged RS256 verification via jwt_verifier.
    - API key   : 32-char hex validated against Redis (auth:apikey:{token}).
    Both paths populate request.state identically and return AuthClaims.
    """

    async def _require_auth(
        request: Request,
        authorization: Optional[str] = Header(None),
    ) -> AuthClaims:
        from ai4icore_exceptions import AuthenticationRequiredError, TokenExpiredError, TokenInvalidError

        if not authorization:
            raise AuthenticationRequiredError()

        # Strip optional "Bearer " scheme prefix — works for both token families.
        token = authorization[7:] if authorization.startswith("Bearer ") else authorization
        if not token:
            raise AuthenticationRequiredError("Empty token.")

        # ── Branch A: opaque API key ──────────────────────────────────────────
        if _is_api_key(token):
            claims = await _validate_api_key(token, request)
            _populate_request_state(request, claims)
            return claims

        # ── Branch B: JWT (RS256) — original path, completely unchanged ───────
        try:
            claims = await jwt_verifier.verify(token)
        except JWTExpiredError:
            raise TokenExpiredError()
        except JWTVerificationError as exc:
            raise TokenInvalidError(exc.message)

        _populate_request_state(request, claims)
        return claims

    return _require_auth


def create_require_role(jwt_verifier: JWTVerifier, *role_names: str):
    """Requires valid JWT or API key + at least one of the specified roles."""
    require_auth = create_require_auth(jwt_verifier)

    async def _require_role(
        claims: AuthClaims = Depends(require_auth),
    ) -> AuthClaims:
        from ai4icore_exceptions import InsufficientPermissionsError

        if PermissionChecker.has_any_role(list(role_names), claims.roles):
            return claims

        raise InsufficientPermissionsError("role", " or ".join(role_names))

    return _require_role
