apiVersion: v1
kind: Secret
metadata:
  name: metrics-service-secret
  namespace: dev
type: Opaque
data:
  # Add your secret environment variables here in base64
  # Example:
  # INFLUXDB_TOKEN: eW91cl9pbmZsdXhkYl90b2tlbg==  # your_influxdb_token in base64
