apiVersion: v1
kind: Secret
metadata:
  name: alerting-service-secret
  namespace: dev
type: Opaque
data:
  # Add your secret environment variables here in base64
  # Example:
  # ALERT_WEBHOOK_URL: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMv  # https://hooks.slack.com/services/ in base64
