"""auto_20260604_112303

Revision ID: 2285db2dfdd5
Revises: f6a7b8c9d0e1
Create Date: 2026-06-04 05:53:03.597258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2285db2dfdd5'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               server_default='PENDING',
               type_=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               server_default=sa.text("'PENDING'::tenant_status_enum"),
               type_=postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
