"""auto_20260622_194951

Revision ID: 34cee9c07750
Revises: b7e1c9a4f2d0
Create Date: 2026-06-22 19:49:51.934072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '34cee9c07750'
down_revision: Union[str, None] = 'b7e1c9a4f2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prev_email', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('prev_phone_number', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'prev_phone_number')
    op.drop_column('users', 'prev_email')
    # ### end Alembic commands ###
