"""auto_20260520_122043

Revision ID: 53a41e6233f1
Revises: 96903e145eea
Create Date: 2026-05-20 06:50:45.606257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53a41e6233f1'
down_revision: Union[str, None] = '96903e145eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # tenants.status: no-op here — default set in c4e8f1a2b3d0 (see aca4be0874b3).
    op.alter_column('users', 'creation_type',
               existing_type=postgresql.ENUM('default', 'google', name='creation_type_enum'),
               type_=sa.Enum('default', 'google', name='creationtype', native_enum=False, length=32),
               existing_nullable=True,
               existing_server_default=sa.text("'default'::creation_type_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'creation_type',
               existing_type=sa.Enum('default', 'google', name='creationtype', native_enum=False, length=32),
               type_=postgresql.ENUM('default', 'google', name='creation_type_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'default'::creation_type_enum"))
