"""users.creation_type: PostgreSQL ENUM → VARCHAR(32)

Revision ID: 53a41e6233f1
Revises: 96903e145eea
Create Date: 2026-05-20 06:50:45.606257

Stores creation_type as VARCHAR (matches auth-service model native_enum=False).
Does not change tenants.status — that is c4e8f1a2b3d0 (+ no-op aca4be0874b3 / 5f775ba90435).

Downgrade restores postgresql.ENUM creation_type_enum.
"""from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53a41e6233f1'
down_revision: Union[str, None] = '96903e145eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('users', 'creation_type',
               existing_type=postgresql.ENUM('default', 'google', name='creation_type_enum'),
               type_=sa.Enum('default', 'google', name='creationtype', native_enum=False, length=32),
               existing_nullable=True,
               existing_server_default=sa.text("'default'::creation_type_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'creation_type',
               existing_type=sa.Enum('default', 'google', name='creationtype', native_enum=False, length=32),
               type_=postgresql.ENUM('default', 'google', name='creation_type_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'default'::creation_type_enum"))
