"""auto_20260520_122043

Revision ID: 53a41e6233f1
Revises: 96903e145eea
Create Date: 2026-05-20 06:50:45.606257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53a41e6233f1'
down_revision: Union[str, None] = '96903e145eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               server_default='PENDING',
               type_=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               existing_nullable=False)
    op.alter_column('users', 'creation_type',
               existing_type=postgresql.ENUM('default', 'google', name='creation_type_enum'),
               type_=sa.Enum('default', 'google', name='creationtype', native_enum=False, length=32),
               existing_nullable=True,
               existing_server_default=sa.text("'default'::creation_type_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'creation_type',
               existing_type=sa.Enum('default', 'google', name='creationtype', native_enum=False, length=32),
               type_=postgresql.ENUM('default', 'google', name='creation_type_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'default'::creation_type_enum"))
    op.alter_column('tenants', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               server_default=sa.text("'PENDING'::tenant_status_enum"),
               type_=postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
