"""auto_20260428_150743

Revision ID: 573a2e08822b
Revises: 7f4b8e2c9a1d
Create Date: 2026-04-28 15:07:44.260369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '573a2e08822b'
down_revision: Union[str, None] = '7f4b8e2c9a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'name',
               existing_type=postgresql.ENUM('users.create', 'users.read', 'users.update', 'users.delete', 'configs.create', 'configs.read', 'configs.update', 'configs.delete', 'metrics.read', 'metrics.export', 'alerts.create', 'alerts.read', 'alerts.update', 'alerts.delete', 'dashboards.create', 'dashboards.read', 'dashboards.update', 'dashboards.delete', 'apiKey.create', 'apiKey.read', 'apiKey.delete', 'apiKey.update', 'service.create', 'service.delete', 'service.update', 'service.read', 'model.create', 'model.read', 'model.update', 'model.delete', 'model.publish', 'model.unpublish', 'roles.assign', 'roles.remove', 'roles.read', 'asr.inference', 'asr.read', 'tts.inference', 'tts.read', 'nmt.inference', 'nmt.read', 'audio-lang-detection.read', 'audio-lang-detection.inference', 'language-detection.read', 'language-detection.inference', 'language-diarization.read', 'language-diarization.inference', 'ner.inference', 'ocr.read', 'ocr.inference', 'speaker-diarization.read', 'speaker-diarization.inference', 'transliteration.read', 'transliteration.inference', 'pipeline.read', 'pipeline.inference', 'llm.read', 'llm.inference', 'model-management.read', 'model-management.inference', 'logs.read', 'traces.read', 'tenant.create', 'tenant.read', 'tenant.update', 'tenant.users.read', 'tenant.users.update', 'pii_guard.inference', 'pii_guard.admin', name='permission_name_enum'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index('ix_permissions_action', table_name='permissions')
    op.drop_index('ix_permissions_resource', table_name='permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_permissions_resource', 'permissions', ['resource'], unique=False)
    op.create_index('ix_permissions_action', 'permissions', ['action'], unique=False)
    op.alter_column('permissions', 'name',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('users.create', 'users.read', 'users.update', 'users.delete', 'configs.create', 'configs.read', 'configs.update', 'configs.delete', 'metrics.read', 'metrics.export', 'alerts.create', 'alerts.read', 'alerts.update', 'alerts.delete', 'dashboards.create', 'dashboards.read', 'dashboards.update', 'dashboards.delete', 'apiKey.create', 'apiKey.read', 'apiKey.delete', 'apiKey.update', 'service.create', 'service.delete', 'service.update', 'service.read', 'model.create', 'model.read', 'model.update', 'model.delete', 'model.publish', 'model.unpublish', 'roles.assign', 'roles.remove', 'roles.read', 'asr.inference', 'asr.read', 'tts.inference', 'tts.read', 'nmt.inference', 'nmt.read', 'audio-lang-detection.read', 'audio-lang-detection.inference', 'language-detection.read', 'language-detection.inference', 'language-diarization.read', 'language-diarization.inference', 'ner.inference', 'ocr.read', 'ocr.inference', 'speaker-diarization.read', 'speaker-diarization.inference', 'transliteration.read', 'transliteration.inference', 'pipeline.read', 'pipeline.inference', 'llm.read', 'llm.inference', 'model-management.read', 'model-management.inference', 'logs.read', 'traces.read', 'tenant.create', 'tenant.read', 'tenant.update', 'tenant.users.read', 'tenant.users.update', 'pii_guard.inference', 'pii_guard.admin', name='permission_name_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
