"""auto_20260527_140730

Revision ID: 7cd128542ccc
Revises: bba2ee748655
Create Date: 2026-05-27 14:07:31.439091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cd128542ccc'
down_revision: Union[str, None] = 'bba2ee748655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               server_default='PENDING',
               type_=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               server_default=sa.text("'PENDING'::tenant_status_enum"),
               type_=postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
