"""auto_20260827_121214

Revision ID: b350e909fe8c
Revises: e9f0a1b2c3d4
Create Date: 2026-08-27 12:12:14.870614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b350e909fe8c'
down_revision: Union[str, None] = 'e9f0a1b2c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_applications_tenant_name_lower', 'applications', ['tenant_id', sa.literal_column('lower(name)')], unique=True)
    op.drop_constraint(op.f('applications_tenant_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('tenants', 'budget_effective_from',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tenants', 'budget_effective_to',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'budget_effective_to',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('tenants', 'budget_effective_from',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('tenants', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               server_default=sa.text("'PENDING'::tenant_status_enum"),
               type_=postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               existing_nullable=False)
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_tenant_id_fkey'), 'applications', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_applications_tenant_name_lower', table_name='applications')
    # ### end Alembic commands ###
