"""auto_20260427_182007

Revision ID: b73fa8d05c10
Revises: d9dcd8093c17
Create Date: 2026-04-27 18:20:08.237563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b73fa8d05c10'
down_revision: Union[str, None] = 'd9dcd8093c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('api_key', 'api_key',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_key', 'api_key',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('api_key', 'expires_at')
    # ### end Alembic commands ###
