"""auto_20260618_180622

Revision ID: b9368b182f74
Revises: b7e1c9a4f2d0
Create Date: 2026-06-18 18:06:25.634057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9368b182f74'
down_revision: Union[str, None] = 'b7e1c9a4f2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               server_default='PENDING',
               type_=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               server_default=sa.text("'PENDING'::tenant_status_enum"),
               type_=postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
