"""auto_20260827_140248

Revision ID: ba737c15e5ec
Revises: e9f0a1b2c3d4
Create Date: 2026-08-27 14:02:48.906344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba737c15e5ec'
down_revision: Union[str, None] = 'e9f0a1b2c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('api_key_application_id_fkey'), 'api_key', type_='foreignkey')
    op.create_foreign_key(None, 'api_key', 'applications', ['application_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               server_default=sa.text("'PENDING'::tenant_status_enum"),
               type_=postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               existing_nullable=False)
    op.drop_constraint(None, 'api_key', type_='foreignkey')
    op.create_foreign_key(op.f('api_key_application_id_fkey'), 'api_key', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
