"""auto_20260527_111212

Revision ID: bba2ee748655
Revises: 7c6c2042521d
Create Date: 2026-05-27 11:12:13.305806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bba2ee748655'
down_revision: Union[str, None] = '7c6c2042521d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               server_default='PENDING',
               type_=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               server_default=sa.text("'PENDING'::tenant_status_enum"),
               type_=postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='tenant_status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
