apiVersion: v1
kind: Service
metadata:
  name: nmt-service
  namespace: dev
  labels:
    app: nmt-service
spec:
  selector:
    app: nmt-service
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmt-service
  namespace: dev
  labels:
    app: nmt-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nmt-service
  template:
    metadata:
      labels:
        app: nmt-service
    spec:
      nodeSelector:
      tolerations:
      - key: "node-type"
        operator: Equal
        value: cpu
        effect: NoSchedule
      initContainers:
      - name: wait-for-db
        image: busybox:1.36
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for DNS and PostgreSQL to be ready..."
          until nslookup postgres.dev.svc.cluster.local && nc -z postgres.dev.svc.cluster.local 5432; do
            echo "Waiting for postgres.dev.svc.cluster.local:5432..."
            sleep 2
          done
          echo "PostgreSQL is ready!"
      containers:
      - name: nmt-service
        image: 662074586476.dkr.ecr.ap-south-1.amazonaws.com/ai4voice/nmt-service:v1.8
        ports:
        - containerPort: 8089
        envFrom:
        - configMapRef:
            name: nmt-service-config
        - secretRef:
            name: nmt-service-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
        startupProbe:
          httpGet:
            path: /health
            port: 8089
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 12
        livenessProbe:
          httpGet:
            path: /health
            port: 8089
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8089
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
