[SERVICE]
    Flush         3
    Daemon        off
    Log_Level     info
    Parsers_File  parsers.conf
    Storage.path  /tmp/fluent-bit/state
    Storage.sync  normal
    Storage.checksum off
    Storage.backlog.mem_limit 5M

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               docker.*
    Refresh_Interval  1
    Mem_Buf_Limit     200MB
    Skip_Long_Lines   Off
    storage.type      memory
    Skip_Empty_Lines  On
    Read_from_Head    Off

[FILTER]
    Name                grep
    Match               docker.*
    Exclude             log /health

[FILTER]
    Name                grep
    Match               docker.*
    Exclude             log /metrics

[FILTER]
    Name                grep
    Match               docker.*
    Exclude             log OPTIONS

[FILTER]
    Name                nest
    Match               docker.*
    Operation           lift
    Nested_under        context
    Add_prefix          ""

[FILTER]
    Name                modify
    Match               docker.*
    Condition           Key_exists status_code
    Rename              status_code statusCode

[FILTER]
    Name                modify
    Match               docker.*
    Add                 collector fluent-bit

[FILTER]
    Name                lua
    Match               docker.*
    Script              /fluent-bit/scripts/extract_context.lua
    Call                extract_context_fields

[FILTER]
    Name                lua
    Match               docker.*
    Script              /fluent-bit/scripts/extract_context.lua
    Call                add_jaeger_url

[OUTPUT]
    Name  opensearch
    Match docker.*
    Host  opensearch
    Port  9200
    Index logs
    Logstash_Format On
    Logstash_Prefix logs
    Logstash_DateFormat %Y.%m.%d
    Retry_Limit 10
    Suppress_Type_Name On
    Generate_ID Off
    Time_Key @timestamp
    Trace_Output Off
    Trace_Error On
