"""auto_20260325_152744

Revision ID: 0d9c0162ef7a
Revises: 1a2b3c4d5e6f
Create Date: 2026-03-25 15:27:44.516032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d9c0162ef7a'
down_revision: Union[str, None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword_library')
    op.drop_table('audit_logs')
    op.drop_table('domain_policies')
    op.drop_table('pattern_library')
    op.drop_table('geo_library')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_library',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('term_text', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('lang_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('term_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('geo_library_pkey'))
    )
    op.create_table('pattern_library',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('lang_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('regex_pattern', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1'::double precision"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pattern_library_pkey')),
    sa.UniqueConstraint('entity_label', 'lang_code', name=op.f('uq_pattern_entity_lang'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('domain_policies',
    sa.Column('domain_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('policy_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('domain_id', name=op.f('domain_policies_pkey'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('domain_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('target_context', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pii_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processing_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trace_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_table('keyword_library',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word_text', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('lang_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('keyword_library_pkey'))
    )
    # ### end Alembic commands ###
