"""auto_20260416_155251

Revision ID: 1136a6462a4d
Revises: 
Create Date: 2026-04-16 15:52:51.843272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1136a6462a4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('domain_id', sa.String(length=50), nullable=True),
    sa.Column('target_context', sa.String(length=20), nullable=True),
    sa.Column('pii_count', sa.Integer(), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('trace_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_policies',
    sa.Column('domain_id', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('policy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('domain_id')
    )
    op.create_table('geo_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_text', sa.String(length=100), nullable=False),
    sa.Column('lang_code', sa.String(length=10), nullable=False),
    sa.Column('term_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_text', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('lang_code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pattern_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_label', sa.String(length=50), nullable=False),
    sa.Column('lang_code', sa.String(length=10), nullable=False),
    sa.Column('regex_pattern', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Float(), server_default=sa.text('1.0'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_label', 'lang_code', name='uq_pattern_entity_lang')
    )
    op.create_table('smr_tenant_policies',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('latency_policy', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('cost_policy', sa.String(length=20), server_default='tier_2', nullable=False),
    sa.Column('accuracy_policy', sa.String(length=20), server_default='standard', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('tenant_pii_domain_map',
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('domain_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_pii_domain_map')
    op.drop_table('smr_tenant_policies')
    op.drop_table('pattern_library')
    op.drop_table('keyword_library')
    op.drop_table('geo_library')
    op.drop_table('domain_policies')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
