"""auto_20260430_175517

Revision ID: 2ce86a6f430d
Revises: 3b7702f315ad
Create Date: 2026-04-30 17:55:18.143537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce86a6f430d'
down_revision: Union[str, None] = '3b7702f315ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quota_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('requests_per_hour', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_quota_configs_name')
    )
    op.create_index(op.f('ix_quota_configs_name'), 'quota_configs', ['name'], unique=True)
    op.create_table('rate_limit_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('requests_per_hour_per_api_key', sa.Integer(), nullable=False),
    sa.Column('requests_per_hour_per_tenant', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_rate_limit_configs_name')
    )
    op.create_index(op.f('ix_rate_limit_configs_name'), 'rate_limit_configs', ['name'], unique=True)
    op.create_table('quota_service_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quota_config_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.String(length=64), nullable=False),
    sa.Column('unit_type', sa.String(length=64), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quota_config_id'], ['quota_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quota_service_limits_quota_config_id'), 'quota_service_limits', ['quota_config_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(length=128), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), server_default='100.00', nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('quota_config_id', sa.UUID(), nullable=False),
    sa.Column('rate_limit_config_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quota_config_id'], ['quota_configs.id'], ),
    sa.ForeignKeyConstraint(['rate_limit_config_id'], ['rate_limit_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_name', name='uq_subscription_plans_plan_name'),
    sa.UniqueConstraint('tier', name='uq_subscription_plans_tier')
    )
    op.create_index(op.f('ix_subscription_plans_tier'), 'subscription_plans', ['tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_plans_tier'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_quota_service_limits_quota_config_id'), table_name='quota_service_limits')
    op.drop_table('quota_service_limits')
    op.drop_index(op.f('ix_rate_limit_configs_name'), table_name='rate_limit_configs')
    op.drop_table('rate_limit_configs')
    op.drop_index(op.f('ix_quota_configs_name'), table_name='quota_configs')
    op.drop_table('quota_configs')
    # ### end Alembic commands ###
