"""ensure pii guard tables exist after autogenerated drops

Revision ID: e8b3d0c1f2a4
Revises: 0d9c0162ef7a
Create Date: 2026-03-25
"""

from alembic import op
import sqlalchemy as sa


revision = "e8b3d0c1f2a4"
down_revision = "0d9c0162ef7a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # `0d9c0162ef7a_auto_20260325_152744` was autogenerated and dropped the
    # PII guard tables because they were not present in the policy-engine
    # SQLAlchemy metadata. This migration restores the PII tables so that
    # `fresh` runs end with a working PII service.

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS pattern_library (
            id SERIAL PRIMARY KEY,
            entity_label VARCHAR(50) NOT NULL,
            lang_code VARCHAR(10) NOT NULL,
            regex_pattern TEXT NOT NULL,
            risk_score FLOAT DEFAULT 1.0,
            is_active BOOLEAN DEFAULT TRUE,
            CONSTRAINT uq_pattern_entity_lang UNIQUE (entity_label, lang_code)
        );
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS geo_library (
            id SERIAL PRIMARY KEY,
            term_text VARCHAR(100) NOT NULL,
            lang_code VARCHAR(10) NOT NULL,
            term_type VARCHAR(20) NOT NULL,
            is_active BOOLEAN DEFAULT TRUE
        );
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS keyword_library (
            id SERIAL PRIMARY KEY,
            word_text VARCHAR(100) NOT NULL,
            category VARCHAR(20) NOT NULL,
            lang_code VARCHAR(10) NOT NULL
        );
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS domain_policies (
            domain_id VARCHAR(50) PRIMARY KEY,
            is_active BOOLEAN DEFAULT FALSE,
            policy_json JSONB NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS audit_logs (
            id SERIAL PRIMARY KEY,
            trace_id UUID,
            tenant_id VARCHAR(50),
            domain_id VARCHAR(50),
            target_context VARCHAR(20),
            pii_count INTEGER,
            processing_ms INTEGER,
            trace_json JSONB,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        """
    )

    # Re-seed the default pattern + geo + keyword libraries. The original
    # `create_pii_tables.py` revision inserted these rows during first creation.
    #
    # If this migration is run on a DB that already has these defaults, the
    # inserts may fail due to uniqueness constraints (pattern_library has a
    # unique constraint). In `fresh` runs they won't exist yet, so this is
    # safe for local dev.

    pattern_table = sa.table(
        "pattern_library",
        sa.column("entity_label", sa.String),
        sa.column("lang_code", sa.String),
        sa.column("regex_pattern", sa.Text),
    )

    op.bulk_insert(
        pattern_table,
        [
            {"entity_label": "AADHAAR_UID", "lang_code": "all", "regex_pattern": r"\b\d{4}[-\s]?\d{4}[-\s]?\d{4}\b"},
            {"entity_label": "PAN_CARD", "lang_code": "all", "regex_pattern": r"\b[A-Z]{5}[0-9]{4}[A-Z]{1}\b"},
            {"entity_label": "PIN_CODE", "lang_code": "all", "regex_pattern": r"\b\d{3}\s?\d{3}\b"},
            {"entity_label": "PHONE", "lang_code": "all", "regex_pattern": r"\b(?:\+91[\-\s]?)?[6-9]\d{9}\b"},
            {"entity_label": "EMAIL", "lang_code": "all", "regex_pattern": r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"},
            {"entity_label": "CREDIT_CARD", "lang_code": "all", "regex_pattern": r"\b(?:\d[ -]*?){13,16}\b"},
            {
                "entity_label": "PERSON",
                "lang_code": "en",
                "regex_pattern": r"(?i)\b(?:Name|Mr\.|Ms\.|Mrs\.)\s+(?:is\s+)?[:\-]?\s*([A-Z][a-z]+(?:\s[A-Z][a-z]+)*)",
            },
            {
                "entity_label": "HOUSE_ANCHOR",
                "lang_code": "en",
                "regex_pattern": r"\b(?:Address|No\.|Flat|House|H\.No|Door|#|Plot|Tower|Wing|Floor|Villa|Apt)\s?[\w\d\-/.,]+\b",
            },
        ],
    )

    geo_table = sa.table(
        "geo_library",
        sa.column("term_text", sa.String),
        sa.column("lang_code", sa.String),
        sa.column("term_type", sa.String),
    )

    op.bulk_insert(
        geo_table,
        [
            {"term_text": "Road", "lang_code": "en", "term_type": "SUFFIX"},
            {"term_text": "Street", "lang_code": "en", "term_type": "SUFFIX"},
            {"term_text": "Nagar", "lang_code": "en", "term_type": "SUFFIX"},
            {"term_text": "Bangalore", "lang_code": "en", "term_type": "SAFE_CITY"},
        ],
    )

    keyword_table = sa.table(
        "keyword_library",
        sa.column("word_text", sa.String),
        sa.column("lang_code", sa.String),
        sa.column("category", sa.String),
    )

    op.bulk_insert(
        keyword_table,
        [
            {"word_text": "farmer", "lang_code": "en", "category": "OCCUPATION"},
            {"word_text": "male", "lang_code": "en", "category": "GENDER"},
        ],
    )


def downgrade() -> None:
    # We intentionally do not drop PII tables in downgrade for safety.
    pass

