"""auto_20260326_174310

Revision ID: ef22aae25ffb
Revises: b3c4d5e6f7a8
Create Date: 2026-03-26 12:13:10.513236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef22aae25ffb'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_pii_domain_map_domain_id'), table_name='tenant_pii_domain_map')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tenant_pii_domain_map_domain_id'), 'tenant_pii_domain_map', ['domain_id'], unique=False)
    # ### end Alembic commands ###
