apiVersion: v1
kind: Service
metadata:
  name: triton-multilingual-asr-service
  namespace: dev
  labels:
    app: triton-multilingual-asr
    component: ai-model
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: grpc
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: metrics
  selector:
    app: triton-multilingual-asr
---
apiVersion: v1
kind: Service
metadata:
  name: triton-multilingual-asr-nodeport
  namespace: dev
  labels:
    app: triton-multilingual-asr
    component: ai-model
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
    name: http
  - port: 8001
    targetPort: 8001
    nodePort: 30081
    protocol: TCP
    name: grpc
  - port: 8002
    targetPort: 8002
    nodePort: 30082
    protocol: TCP
    name: metrics
  selector:
    app: triton-multilingual-asr


