"""auto_20260309_161154

Revision ID: 37a8d2ea829f
Revises: 
Create Date: 2026-03-09 16:11:55.119104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37a8d2ea829f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_config_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=100), nullable=True),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('before_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_changed_at', 'alert_config_audit_log', ['changed_at'], unique=False)
    op.create_index('idx_audit_log_changed_by', 'alert_config_audit_log', ['changed_by'], unique=False)
    op.create_index('idx_audit_log_organization', 'alert_config_audit_log', ['organization'], unique=False)
    op.create_index('idx_audit_log_table_record', 'alert_config_audit_log', ['table_name', 'record_id'], unique=False)
    op.create_table('alert_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('promql_expr', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), server_default='application', nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('urgency', sa.String(length=20), server_default='medium', nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('evaluation_interval', sa.String(length=20), server_default='30s', nullable=True),
    sa.Column('for_duration', sa.String(length=20), server_default='5m', nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('threshold_value', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('threshold_unit', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization', 'name', name='unique_organization_alert_name')
    )
    op.create_index('idx_alert_definitions_category', 'alert_definitions', ['category'], unique=False)
    op.create_index('idx_alert_definitions_enabled', 'alert_definitions', ['enabled'], unique=False)
    op.create_index('idx_alert_definitions_organization', 'alert_definitions', ['organization'], unique=False)
    op.create_index('idx_alert_definitions_organization_enabled', 'alert_definitions', ['organization', 'enabled'], unique=False)
    op.create_index('idx_alert_definitions_severity', 'alert_definitions', ['severity'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('operator', sa.String(length=10), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('evaluation_window', sa.Integer(), server_default='300', nullable=True),
    sa.Column('notification_channels', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_alert_rules_active', 'alert_rules', ['is_active'], unique=False)
    op.create_index('idx_alert_rules_metric_name', 'alert_rules', ['metric_name'], unique=False)
    op.create_index('idx_alert_rules_name', 'alert_rules', ['name'], unique=False)
    op.create_table('anomaly_detection_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('model_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('training_data_size', sa.Integer(), nullable=False),
    sa.Column('last_trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('accuracy_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anomaly_models_active', 'anomaly_detection_models', ['is_active'], unique=False)
    op.create_index('idx_anomaly_models_last_trained', 'anomaly_detection_models', ['last_trained_at'], unique=False)
    op.create_index('idx_anomaly_models_metric_name', 'anomaly_detection_models', ['metric_name'], unique=False)
    op.create_table('escalation_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_escalation_policies_name', 'escalation_policies', ['name'], unique=False)
    op.create_table('notification_receivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=100), nullable=False),
    sa.Column('receiver_name', sa.String(length=255), nullable=False),
    sa.Column('email_to', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('email_subject_template', sa.Text(), nullable=True),
    sa.Column('email_body_template', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization', 'receiver_name', name='unique_organization_receiver_name')
    )
    op.create_index('idx_notification_receivers_enabled', 'notification_receivers', ['enabled'], unique=False)
    op.create_index('idx_notification_receivers_organization', 'notification_receivers', ['organization'], unique=False)
    op.create_table('alert_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_definition_id', sa.Integer(), nullable=False),
    sa.Column('annotation_key', sa.String(length=50), nullable=False),
    sa.Column('annotation_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['alert_definition_id'], ['alert_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_definition_id', 'annotation_key', name='unique_alert_annotation_key')
    )
    op.create_index('idx_alert_annotations_alert_def_id', 'alert_annotations', ['alert_definition_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='firing', nullable=True),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_fired_at', 'alerts', ['fired_at'], unique=False)
    op.create_index('idx_alerts_metric_name', 'alerts', ['metric_name'], unique=False)
    op.create_index('idx_alerts_rule_id', 'alerts', ['rule_id'], unique=False)
    op.create_index('idx_alerts_rule_status', 'alerts', ['rule_id', 'status'], unique=False)
    op.create_index('idx_alerts_status', 'alerts', ['status'], unique=False)
    op.create_table('routing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('match_severity', sa.String(length=20), nullable=True),
    sa.Column('match_category', sa.String(length=50), nullable=True),
    sa.Column('match_alert_type', sa.String(length=50), nullable=True),
    sa.Column('group_by', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('group_wait', sa.String(length=20), server_default='10s', nullable=True),
    sa.Column('group_interval', sa.String(length=20), server_default='10s', nullable=True),
    sa.Column('repeat_interval', sa.String(length=20), server_default='12h', nullable=True),
    sa.Column('continue_routing', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['notification_receivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization', 'rule_name', name='unique_organization_rule_name')
    )
    op.create_index('idx_routing_rules_enabled', 'routing_rules', ['enabled'], unique=False)
    op.create_index('idx_routing_rules_match_category', 'routing_rules', ['match_category'], unique=False)
    op.create_index('idx_routing_rules_match_severity', 'routing_rules', ['match_severity'], unique=False)
    op.create_index('idx_routing_rules_organization', 'routing_rules', ['organization'], unique=False)
    op.create_index('idx_routing_rules_priority', 'routing_rules', ['priority'], unique=False)
    op.create_index('idx_routing_rules_receiver_id', 'routing_rules', ['receiver_id'], unique=False)
    op.create_table('notification_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_history_alert_id', 'notification_history', ['alert_id'], unique=False)
    op.create_index('idx_notification_history_sent_at', 'notification_history', ['sent_at'], unique=False)
    op.create_index('idx_notification_history_status', 'notification_history', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notification_history_status', table_name='notification_history')
    op.drop_index('idx_notification_history_sent_at', table_name='notification_history')
    op.drop_index('idx_notification_history_alert_id', table_name='notification_history')
    op.drop_table('notification_history')
    op.drop_index('idx_routing_rules_receiver_id', table_name='routing_rules')
    op.drop_index('idx_routing_rules_priority', table_name='routing_rules')
    op.drop_index('idx_routing_rules_organization', table_name='routing_rules')
    op.drop_index('idx_routing_rules_match_severity', table_name='routing_rules')
    op.drop_index('idx_routing_rules_match_category', table_name='routing_rules')
    op.drop_index('idx_routing_rules_enabled', table_name='routing_rules')
    op.drop_table('routing_rules')
    op.drop_index('idx_alerts_status', table_name='alerts')
    op.drop_index('idx_alerts_rule_status', table_name='alerts')
    op.drop_index('idx_alerts_rule_id', table_name='alerts')
    op.drop_index('idx_alerts_metric_name', table_name='alerts')
    op.drop_index('idx_alerts_fired_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('idx_alert_annotations_alert_def_id', table_name='alert_annotations')
    op.drop_table('alert_annotations')
    op.drop_index('idx_notification_receivers_organization', table_name='notification_receivers')
    op.drop_index('idx_notification_receivers_enabled', table_name='notification_receivers')
    op.drop_table('notification_receivers')
    op.drop_index('idx_escalation_policies_name', table_name='escalation_policies')
    op.drop_table('escalation_policies')
    op.drop_index('idx_anomaly_models_metric_name', table_name='anomaly_detection_models')
    op.drop_index('idx_anomaly_models_last_trained', table_name='anomaly_detection_models')
    op.drop_index('idx_anomaly_models_active', table_name='anomaly_detection_models')
    op.drop_table('anomaly_detection_models')
    op.drop_index('idx_alert_rules_name', table_name='alert_rules')
    op.drop_index('idx_alert_rules_metric_name', table_name='alert_rules')
    op.drop_index('idx_alert_rules_active', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index('idx_alert_definitions_severity', table_name='alert_definitions')
    op.drop_index('idx_alert_definitions_organization_enabled', table_name='alert_definitions')
    op.drop_index('idx_alert_definitions_organization', table_name='alert_definitions')
    op.drop_index('idx_alert_definitions_enabled', table_name='alert_definitions')
    op.drop_index('idx_alert_definitions_category', table_name='alert_definitions')
    op.drop_table('alert_definitions')
    op.drop_index('idx_audit_log_table_record', table_name='alert_config_audit_log')
    op.drop_index('idx_audit_log_organization', table_name='alert_config_audit_log')
    op.drop_index('idx_audit_log_changed_by', table_name='alert_config_audit_log')
    op.drop_index('idx_audit_log_changed_at', table_name='alert_config_audit_log')
    op.drop_table('alert_config_audit_log')
    # ### end Alembic commands ###
