"""auto_20260602_064040

Revision ID: 13c752281217
Revises: 961e254313e2
Create Date: 2026-06-02 06:40:43.481077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c752281217'
down_revision: Union[str, None] = '961e254313e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mm_services', sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('mm_services', sa.Column('billing_unit_type', sa.String(length=32), nullable=True))
    op.add_column('mm_services', sa.Column('tier', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mm_services', 'tier')
    op.drop_column('mm_services', 'billing_unit_type')
    op.drop_column('mm_services', 'cost_per_unit')
    # ### end Alembic commands ###
