"""auto_20260425_120953

Revision ID: 1df5f5c5f309
Revises: 
Create Date: 2026-04-25 12:09:54.016763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1df5f5c5f309'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mm_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('version_status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', 'ARCHIVED', name='version_status_enum'), nullable=False),
    sa.Column('version_status_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ref_url', sa.String(length=500), nullable=True),
    sa.Column('task', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('domain', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inference_endpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('benchmarks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_mm_models_name_version')
    )
    op.create_index(op.f('ix_mm_models_model_id'), 'mm_models', ['model_id'], unique=True)
    op.create_table('mm_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('hardware_description', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('health_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('benchmarks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('unpublished_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('inference_server_type', sa.String(length=32), server_default='triton', nullable=False),
    sa.Column('ssl_verify', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['mm_models.model_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mm_services_model_id'), 'mm_services', ['model_id'], unique=False)
    op.create_index(op.f('ix_mm_services_service_id'), 'mm_services', ['service_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mm_services_service_id'), table_name='mm_services')
    op.drop_index(op.f('ix_mm_services_model_id'), table_name='mm_services')
    op.drop_table('mm_services')
    op.drop_index(op.f('ix_mm_models_model_id'), table_name='mm_models')
    op.drop_table('mm_models')
    # ### end Alembic commands ###
