"""auto_20260608_124538

Revision ID: 2e58f4d3862e
Revises: d7b2c4e6f8a1
Create Date: 2026-06-08 12:45:41.216927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e58f4d3862e'
down_revision: Union[str, None] = 'd7b2c4e6f8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mm_services', sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('mm_services', sa.Column('billing_unit_type', sa.String(length=32), nullable=True))
    op.add_column('mm_services', sa.Column('tier', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mm_services', 'tier')
    op.drop_column('mm_services', 'billing_unit_type')
    op.drop_column('mm_services', 'cost_per_unit')
    # ### end Alembic commands ###
