"""auto_20260527_111218

Revision ID: 31d7bc3f4379
Revises: f7e8d9c0b1a2
Create Date: 2026-05-27 11:12:18.918359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d7bc3f4379'
down_revision: Union[str, None] = 'f7e8d9c0b1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quota_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('requests_per_hour', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_quota_configs_name')
    )
    op.create_index(op.f('ix_quota_configs_name'), 'quota_configs', ['name'], unique=True)
    op.create_table('quota_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=128), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('requests_used', sa.Integer(), nullable=False),
    sa.Column('units_used', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quota_usage_service_id'), 'quota_usage', ['service_id'], unique=False)
    op.create_index(op.f('ix_quota_usage_tenant_id'), 'quota_usage', ['tenant_id'], unique=False)
    op.create_table('rate_limit_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('requests_per_hour_per_api_key', sa.Integer(), nullable=False),
    sa.Column('requests_per_hour_per_tenant', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_rate_limit_configs_name')
    )
    op.create_index(op.f('ix_rate_limit_configs_name'), 'rate_limit_configs', ['name'], unique=True)
    op.create_table('usage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('api_key_id', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=128), nullable=False),
    sa.Column('units_consumed', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('cost', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('rate_used', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('tier', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_api_key_id'), 'usage_records', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_usage_records_service_id'), 'usage_records', ['service_id'], unique=False)
    op.create_index(op.f('ix_usage_records_tenant_id'), 'usage_records', ['tenant_id'], unique=False)
    op.create_table('wallet_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('total_plan_cost', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('total_used', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_balances_tenant_id'), 'wallet_balances', ['tenant_id'], unique=True)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('reference_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_tenant_id'), 'wallet_transactions', ['tenant_id'], unique=False)
    op.create_table('quota_service_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quota_config_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.String(length=64), nullable=False),
    sa.Column('unit_type', sa.String(length=64), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quota_config_id'], ['quota_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quota_service_limits_quota_config_id'), 'quota_service_limits', ['quota_config_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(length=128), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), server_default='100.00', nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('quota_config_id', sa.UUID(), nullable=False),
    sa.Column('rate_limit_config_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quota_config_id'], ['quota_configs.id'], ),
    sa.ForeignKeyConstraint(['rate_limit_config_id'], ['rate_limit_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_name', name='uq_subscription_plans_plan_name'),
    sa.UniqueConstraint('tier', name='uq_subscription_plans_tier')
    )
    op.create_index(op.f('ix_subscription_plans_tier'), 'subscription_plans', ['tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_plans_tier'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_quota_service_limits_quota_config_id'), table_name='quota_service_limits')
    op.drop_table('quota_service_limits')
    op.drop_index(op.f('ix_wallet_transactions_tenant_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_wallet_balances_tenant_id'), table_name='wallet_balances')
    op.drop_table('wallet_balances')
    op.drop_index(op.f('ix_usage_records_tenant_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_service_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_api_key_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_rate_limit_configs_name'), table_name='rate_limit_configs')
    op.drop_table('rate_limit_configs')
    op.drop_index(op.f('ix_quota_usage_tenant_id'), table_name='quota_usage')
    op.drop_index(op.f('ix_quota_usage_service_id'), table_name='quota_usage')
    op.drop_table('quota_usage')
    op.drop_index(op.f('ix_quota_configs_name'), table_name='quota_configs')
    op.drop_table('quota_configs')
    # ### end Alembic commands ###
