"""auto_20260827_121623

Revision ID: 368f3af890ad
Revises: d4e5f6a7b8c9
Create Date: 2026-08-27 12:16:23.755219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368f3af890ad'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget_usage', 'api_key_budget_used',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default='0',
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget_usage', 'api_key_budget_used',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
