"""create_inference_types_table

Creates `inference_types`, the DB-resident catalogue of billable inference
types that replaces the deploy-time YAML at
`libs/ai4i_core/ai4i_core/ppu/inference_types.yaml`.

Motivation (spec: services/platform-core-service/spec/db-migration-based-inference-type.md):
  - admins can add/edit inference types without a deploy
  - `ppu_tier_quotas` / `ppu_quota_usage` gain a real FK target instead of the
    free-text `inference_name` column (that FK cutover is a separate, later
    migration — see 2935_IMPLEMENTATION.md §7.2)

`endpoint_patterns` is TEXT[] rather than a scalar because one type can be
served on several paths — today only `llm` (/api/v1/chat and
/api/v1/chat/completions), which the YAML models as `endpoint_aliases`.

This migration is DDL only; the 12 catalogue rows are seeded by b41ed153cac5
so the schema change and the data load can be rolled back independently.

Nothing reads this table yet — the YAML stays authoritative until the route and
schema cutover in 2935_IMPLEMENTATION.md §7.1.

Revision ID: 3b6faeb2bff6
Revises: 1edf17b191a7
Create Date: 2026-08-26 16:50:14.080303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b6faeb2bff6'
down_revision: Union[str, None] = '1edf17b191a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('endpoint_patterns', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('pricing', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_inference_types_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inference_types')
    # ### end Alembic commands ###
