"""auto_20260708_133318

Revision ID: 5c6faec0df77
Revises: d4e6f8a1b3c5
Create Date: 2026-07-08 13:33:18.770866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6faec0df77'
down_revision: Union[str, None] = 'd4e6f8a1b3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppu_tier_quotas', sa.Column('pending_monthly_quota', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ppu_tier_quotas', 'pending_monthly_quota')
    # ### end Alembic commands ###
