"""auto_20260427_113132

Revision ID: 908da7983d98
Revises: b8a6e529935f
Create Date: 2026-04-27 11:31:33.052945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '908da7983d98'
down_revision: Union[str, None] = 'b8a6e529935f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mm_services', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('mm_services', 'unpublished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('fk_mm_services_model_id'), 'mm_services', type_='foreignkey')
    op.create_foreign_key('fk_mm_services_model_id', 'mm_services', 'mm_models', ['model_id'], ['model_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_mm_services_model_id', 'mm_services', type_='foreignkey')
    op.create_foreign_key(op.f('fk_mm_services_model_id'), 'mm_services', 'mm_models', ['model_id'], ['model_id'], ondelete='RESTRICT')
    op.alter_column('mm_services', 'unpublished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('mm_services', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###
