"""auto_20260827_140334

Revision ID: 9ae8275aebfd
Revises: d4e5f6a7b8c9
Create Date: 2026-08-27 14:03:35.255808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae8275aebfd'
down_revision: Union[str, None] = '36e2308271e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_usage_api_key_id'), table_name='budget_usage')
    op.create_unique_constraint(None, 'budget_usage', ['api_key_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budget_usage', type_='unique')
    op.create_index(op.f('ix_budget_usage_api_key_id'), 'budget_usage', ['api_key_id'], unique=False)
    # ### end Alembic commands ###
