"""auto_20260601_063814

Revision ID: ad70c31a8ef3
Revises: b9e3f1a2c4d5
Create Date: 2026-06-01 06:38:17.742025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad70c31a8ef3'
down_revision: Union[str, None] = 'b9e3f1a2c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mm_services', sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('mm_services', sa.Column('billing_unit_type', sa.String(length=32), nullable=True))
    op.add_column('mm_services', sa.Column('tier', sa.String(length=20), nullable=True))
    op.drop_column('mm_services', 'adapter_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mm_services', sa.Column('adapter_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('mm_services', 'tier')
    op.drop_column('mm_services', 'billing_unit_type')
    op.drop_column('mm_services', 'cost_per_unit')
    # ### end Alembic commands ###
