"""add pii policy tables

Creates the policy data model declared in
services/platform-core-service/app/models/policy_management/: category,
sub_category, policy_type, policy and audit_log.

The companion column applications.policy_id lives in the auth DB and is
added by ai4iplatform_auth/51379ee0d696_add_policy_id_to_applications.py.

Postgres has no foreign keys on array elements, so policy.policy_type_id
(-> policy_type.id) and audit_log.policy_id (-> policy.id) are not enforced
by the database; the application layer must validate them.

Revision ID: e3df9d24b593
Revises: 7a3c9e1f5b2d
Create Date: 2026-10-08 17:10:11.004129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3df9d24b593'
down_revision: Union[str, None] = '7a3c9e1f5b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_id', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('model_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('guardrail_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_trace_id'), 'audit_log', ['trace_id'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_category_name')
    )
    op.create_table('policy_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_type', sa.String(length=100), nullable=False),
    sa.Column('policy_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_type', name='uq_policy_type_policy_type')
    )
    op.create_table('sub_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_sub_category_category_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_sub_category_name')
    )
    op.create_index(op.f('ix_sub_category_category_id'), 'sub_category', ['category_id'], unique=False)
    op.create_table('policy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('guardrail_scope', sa.Enum('input', 'output', 'both', name='guardrail_scope_enum'), nullable=False),
    sa.Column('is_global', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('sub_category_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('policy_type_id', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_category.id'], name='fk_policy_sub_category_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_policy_name'),
    sa.UniqueConstraint('policy_id', name='uq_policy_policy_id')
    )
    op.create_index(op.f('ix_policy_sub_category_id'), 'policy', ['sub_category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_sub_category_id'), table_name='policy')
    op.drop_table('policy')
    op.drop_index(op.f('ix_sub_category_category_id'), table_name='sub_category')
    op.drop_table('sub_category')
    op.drop_table('policy_type')
    op.drop_table('category')
    op.drop_index(op.f('ix_audit_log_trace_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
    # drop_table() does not drop the enum that create_table() created.
    sa.Enum(name='guardrail_scope_enum').drop(op.get_bind(), checkfirst=True)
