[alembic]
# Point script_location to the Alembic directory under migrations/postgres
script_location = %(here)s/alembic
prepend_sys_path = .
revision_environment = true
version_locations = %(here)s/alembic/versions/ai4iplatform_auth:%(here)s/alembic/versions/ai4iplatform_core:%(here)s/alembic/versions/alerting_db:%(here)s/alembic/versions/ai4i_platform_db:%(here)s/alembic/versions/policy_db
version_path_separator = os
sqlalchemy.url = postgresql+psycopg2://placeholder:placeholder@localhost/placeholder

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
