apiVersion: v1
kind: Service
metadata:
  name: tts-service
  namespace: dev
  labels:
    app: tts-service
spec:
  selector:
    app: tts-service
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-service
  namespace: dev
  labels:
    app: tts-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tts-service
  template:
    metadata:
      labels:
        app: tts-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - ip-30-0-4-22.ap-south-1.compute.internal
      nodeSelector:
      tolerations:
      - key: "node-type"
        operator: Equal
        value: cpu
        effect: NoSchedule
      initContainers:
      - name: wait-for-db
        image: busybox:1.36
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for PostgreSQL to be ready..."
          MAX_ATTEMPTS=60
          ATTEMPT=0
          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
            if nc -z postgres.dev.svc.cluster.local 5432 2>/dev/null; then
              echo "PostgreSQL is ready!"
              exit 0
            fi
            ATTEMPT=$((ATTEMPT + 1))
            echo "Attempt $ATTEMPT/$MAX_ATTEMPTS: Waiting for postgres.dev.svc.cluster.local:5432..."
            sleep 2
          done
          echo "ERROR: PostgreSQL not available after $MAX_ATTEMPTS attempts"
          exit 1
      containers:
      - name: tts-service
        image: 662074586476.dkr.ecr.ap-south-1.amazonaws.com/ai4voice/tts-service:v1.0
        ports:
        - containerPort: 8088
        envFrom:
        - configMapRef:
            name: tts-service-config
        - secretRef:
            name: tts-service-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "2Gi"
            cpu: "600m"
        startupProbe:
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 12
        livenessProbe:
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
