"""auto_20260408_113047

Revision ID: 2877811d16d8
Revises: 0001_policy_service
Create Date: 2026-04-08 11:30:47.555130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2877811d16d8'
down_revision: Union[str, None] = '0001_policy_service'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pii_policy', 'supported_languages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('pii_policy_name_key'), 'pii_policy', type_='unique')
    op.drop_index(op.f('ix_pii_policy_name'), table_name='pii_policy')
    op.create_index(op.f('ix_pii_policy_name'), 'pii_policy', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pii_policy_name'), table_name='pii_policy')
    op.create_index(op.f('ix_pii_policy_name'), 'pii_policy', ['name'], unique=False)
    op.create_unique_constraint(op.f('pii_policy_name_key'), 'pii_policy', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('pii_policy', 'supported_languages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    # ### end Alembic commands ###
