"""auto_20260416_155300

Revision ID: eeb2648f856c
Revises: 
Create Date: 2026-04-16 15:53:01.182841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eeb2648f856c'
down_revision: Union[str, None] = '0001_policy_service'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pii_policy',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_global', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('supported_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_index(op.f('ix_pii_policy_name'), 'pii_policy', ['name'], unique=True)
    op.create_table('pii_types',
    sa.Column('pii_type_id', sa.UUID(), nullable=False),
    sa.Column('pii_type_label', sa.String(length=255), nullable=False),
    sa.Column('regex_pattern', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('mask_format', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pii_type_id'),
    sa.UniqueConstraint('pii_type_label', name='uq_pii_type_label')
    )
    op.create_index(op.f('ix_pii_types_pii_type_label'), 'pii_types', ['pii_type_label'], unique=False)
    op.create_table('policy_pii_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('pii_type_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pii_type_id'], ['pii_types.pii_type_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['pii_policy.policy_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'pii_type_id', name='uq_policy_pii_type')
    )
    op.create_index(op.f('ix_policy_pii_types_pii_type_id'), 'policy_pii_types', ['pii_type_id'], unique=False)
    op.create_index(op.f('ix_policy_pii_types_policy_id'), 'policy_pii_types', ['policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_pii_types_policy_id'), table_name='policy_pii_types')
    op.drop_index(op.f('ix_policy_pii_types_pii_type_id'), table_name='policy_pii_types')
    op.drop_table('policy_pii_types')
    op.drop_index(op.f('ix_pii_types_pii_type_label'), table_name='pii_types')
    op.drop_table('pii_types')
    op.drop_index(op.f('ix_pii_policy_name'), table_name='pii_policy')
    op.drop_table('pii_policy')
    # ### end Alembic commands ###
