apiVersion: v1
kind: Service
metadata:
  name: pipeline-service
  namespace: dev
  labels:
    app: pipeline-service
spec:
  selector:
    app: pipeline-service
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-service
  namespace: dev
  labels:
    app: pipeline-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-service
  template:
    metadata:
      labels:
        app: pipeline-service
    spec:
      nodeSelector:
      tolerations:
      - key: "node-type"
        operator: Equal
        value: cpu
        effect: NoSchedule
      containers:
      - name: pipeline-service
        image: ai4v/pipeline-service:latest
        ports:
        - containerPort: 8090
        env:
        - name: ENV_FILE
          value: ".env"
        envFrom:
        - configMapRef:
            name: pipeline-service-config
        - secretRef:
            name: pipeline-service-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
