apiVersion: v1
kind: Secret
metadata:
  name: pipeline-service-secret
  namespace: dev
type: Opaque
data:
  # Add your secret environment variables here in base64
  # Example:
  # PIPELINE_API_KEY: eW91cl9waXBlbGluZV9hcGlfa2V5  # your_pipeline_api_key in base64
