apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  namespace: dev
type: Opaque
data:
  ELASTIC_PASSWORD: ZWxhc3RpY3Bhc3M=  # elasticpass in base64
  ELASTIC_USERNAME: ZWxhc3RpYw==  # elastic in base64
