"""
Constants package for all services.
"""
from .error_messages import *

__all__ = [
    # ASR Error Codes
    'LANGUAGE_NOT_SUPPORTED',
    'SERVICE_UNAVAILABLE',
    'PROCESSING_TIMEOUT',
    'QUOTA_EXCEEDED',
    'MODEL_UNAVAILABLE',
    'RATE_LIMIT_EXCEEDED',
    'POOR_AUDIO_QUALITY',
    'INVALID_REQUEST',
    'AUTH_FAILED',
    'TENANT_SUSPENDED',
    'NO_FILE_SELECTED',
    'UNSUPPORTED_FORMAT',
    'FILE_TOO_LARGE',
    'INVALID_FILE',
    'UPLOAD_FAILED',
    'AUDIO_TOO_SHORT',
    'AUDIO_TOO_LONG',
    'EMPTY_AUDIO_FILE',
    'UPLOAD_TIMEOUT',
    # ASR Error Messages
    'LANGUAGE_NOT_SUPPORTED_MESSAGE',
    'SERVICE_UNAVAILABLE_MESSAGE',
    'PROCESSING_TIMEOUT_MESSAGE',
    'QUOTA_EXCEEDED_MESSAGE',
    'MODEL_UNAVAILABLE_MESSAGE',
    'RATE_LIMIT_EXCEEDED_MESSAGE',
    'POOR_AUDIO_QUALITY_MESSAGE',
    'INVALID_REQUEST_MESSAGE',
    'AUTH_FAILED_MESSAGE',
    'TENANT_SUSPENDED_MESSAGE',
    'NO_FILE_SELECTED_MESSAGE',
    'UNSUPPORTED_FORMAT_MESSAGE',
    'FILE_TOO_LARGE_MESSAGE',
    'INVALID_FILE_MESSAGE',
    'UPLOAD_FAILED_MESSAGE',
    'AUDIO_TOO_SHORT_MESSAGE',
    'AUDIO_TOO_LONG_MESSAGE',
    'EMPTY_AUDIO_FILE_MESSAGE',
    'UPLOAD_TIMEOUT_MESSAGE',
]
