groups:
- name: application-alerts
  interval: 30s
  rules:
  - alert: tezst 2
    expr: histogram_quantile(0.5, sum by (le, endpoint, tenant) (rate(telemetry_obsv_request_duration_seconds_bucket{endpoint=~"/.*inference.*", service=~"ocr\-service|speaker\-diarization\-service"}[5m]))) < 0.002
    for: 1m
    labels:
      severity: warning
      urgency: medium
      category: application
      alert_type: Latency
    annotations:
      summary: tezst 2
      description: null
