"""auto_20260420_160322

Revision ID: 15a01d64a949
Revises: 81aa5feb3b29
Create Date: 2026-04-20 10:33:25.043770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a01d64a949'
down_revision: Union[str, None] = '81aa5feb3b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setup_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setup_tokens_id'), 'setup_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_setup_tokens_token'), 'setup_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_setup_tokens_user_id'), 'setup_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_setup_tokens_user_id'), table_name='setup_tokens')
    op.drop_index(op.f('ix_setup_tokens_token'), table_name='setup_tokens')
    op.drop_index(op.f('ix_setup_tokens_id'), table_name='setup_tokens')
    op.drop_table('setup_tokens')
    # ### end Alembic commands ###
