"""auto_20260430_175522

Revision ID: 0f5e08f969ab
Revises: 480033fae93d
Create Date: 2026-04-30 17:55:22.991687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f5e08f969ab'
down_revision: Union[str, None] = '480033fae93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(length=128), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('plan_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quota_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('rate_limit_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('allowed_services', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_plans_plan_id'), 'tenant_plans', ['plan_id'], unique=False)
    op.create_index(op.f('ix_tenant_plans_tenant_id'), 'tenant_plans', ['tenant_id'], unique=False)
    op.add_column('service_config', sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('service_config', sa.Column('tier', sa.String(length=20), nullable=True))
    op.add_column('service_config', sa.Column('billing_unit_type', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_service_config_tier'), 'service_config', ['tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_config_tier'), table_name='service_config')
    op.drop_column('service_config', 'billing_unit_type')
    op.drop_column('service_config', 'tier')
    op.drop_column('service_config', 'cost_per_unit')
    op.drop_index(op.f('ix_tenant_plans_tenant_id'), table_name='tenant_plans')
    op.drop_index(op.f('ix_tenant_plans_plan_id'), table_name='tenant_plans')
    op.drop_table('tenant_plans')
    # ### end Alembic commands ###
