"""auto_20260325_152748

Revision ID: 55d098456553
Revises: 5420a5259ea1
Create Date: 2026-03-25 15:27:49.287271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d098456553'
down_revision: Union[str, None] = '5420a5259ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_users', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='tenantuserstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('user_billing_records', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='tenantuserstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_billing_records', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='tenantuserstatus', native_enum=False),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('tenant_users', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='tenantuserstatus', native_enum=False),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###
