"""auto_20260312_141349

Revision ID: 9a2927bdc4f7
Revises: 8d5eddc014c0
Create Date: 2026-03-12 14:13:52.151067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a2927bdc4f7'
down_revision: Union[str, None] = '8d5eddc014c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('email_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_tenants_email_hash'), 'tenants', ['email_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_email_hash'), table_name='tenants')
    op.drop_column('tenants', 'email_hash')
    # ### end Alembic commands ###
