"""auto_20260417_145453

Revision ID: c4df04419e77
Revises: 5637dfb48268
Create Date: 2026-04-17 09:24:54.976706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4df04419e77'
down_revision: Union[str, None] = '5637dfb48268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_users', sa.Column('suspension_tag', sa.Enum('ADMIN_SUSPENDED', 'TENANT_SUSPENDED', name='tenantusersuspensiontag', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_users', 'suspension_tag')
    # ### end Alembic commands ###
